backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "home"
    label: "Home Page"
    files:
      - file: "home.json"
        label: "Home Content"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "About Us", name: "about", widget: "text"}
